# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This is an example of how to define an OAM Domain. For details about the fields in domain specification, refer https://oracle.github.io/weblogic-kubernetes-operator/managing-domains/domain-resource/
#
apiVersion: "weblogic.oracle/v9"
kind: Domain
metadata:
  name: %DOMAIN_UID%
  namespace: %NAMESPACE%
  labels:
    weblogic.domainUID: %DOMAIN_UID%
spec:
  # The WebLogic Domain Home
  domainHome: %DOMAIN_HOME%

  # The domain home source type
  # Set to PersistentVolume for domain-in-pv, Image for domain-in-image, or FromModel for model-in-image
  domainHomeSourceType: PersistentVolume

  # The WebLogic Server image that the Operator uses to start the domain
  image: "%OAM_IMAGE%"

  # imagePullPolicy defaults to "Always" if image version is :latest
  imagePullPolicy: IfNotPresent

  # Add additional secret name if you are using a different registry for domain creation image.
  # Identify which Secret contains the credentials for pulling an image
  %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%imagePullSecrets:
  %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%- name: %WEBLOGIC_IMAGE_PULL_SECRET_NAME%
  # Identify which Secret contains the WebLogic Admin credentials
  webLogicCredentialsSecret:
    name: %DOMAIN_UID%-weblogic-credentials

  # Whether to include the server out file into the pod's stdout, default is true
  includeServerOutInPodLog: true

  # Whether to enable log home
  logHomeEnabled: true

  # Whether to write HTTP access log file to log home
  httpAccessLogInLogHome: true

  # The in-pod location for domain log, server logs, server out, introspector out, and Node Manager log files
  logHome: %LOG_HOME%
  # An (optional) in-pod location for data storage of default and custom file stores.
  # If not specified or the value is either not set or empty (e.g. dataHome: "") then the
  # data storage directories are determined from the WebLogic domain home configuration.
  dataHome: ""

  # serverStartPolicy legal values are "Never, "IfNeeded", or "AdminOnly"
  # This determines which WebLogic Servers the Operator will start up when it discovers this Domain
  # - "Never" will not start any server in the domain
  # - "AdminOnly" will start up only the administration server (no managed servers will be started)
  # - "IfNeeded" will start all non-clustered servers, including the administration server and clustered servers up to the replica count
  serverStartPolicy: IfNeeded

  serverPod:
    initContainers:
      #DO NOT CHANGE THE NAME OF THIS INIT CONTAINER
      - name: compat-connector-init
        # OAM Product image, same as spec.image mentioned above
        image: "%OAM_IMAGE%"
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "mkdir -p  %DOMAIN_ROOT_DIR%/domains/wdt-logs"]
        volumeMounts:
          - mountPath: %DOMAIN_ROOT_DIR%
            name: weblogic-domain-storage-volume
    # a mandatory list of environment variable to be set on the servers
    env:
    - name: JAVA_OPTIONS
      value: %JAVA_OPTIONS%
    - name: USER_MEM_ARGS
      value: "-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx1024m "
    - name: WLSDEPLOY_LOG_DIRECTORY
      value: "%DOMAIN_ROOT_DIR%/domains/wdt-logs"
    - name: WLSDEPLOY_PROPERTIES
      value: "-Dwdt.config.disable.rcu.drop.schema=true"
    volumes:
    - name: weblogic-domain-storage-volume
      persistentVolumeClaim:
        claimName: %DOMAIN_UID%-domain-pvc
    volumeMounts:
    - mountPath: %DOMAIN_ROOT_DIR%
      name: weblogic-domain-storage-volume

  # adminServer is used to configure the desired behavior for starting the administration server.
  adminServer:
    %EXPOSE_ANY_CHANNEL_PREFIX%adminService:
    %EXPOSE_ANY_CHANNEL_PREFIX%  channels:
    # The Admin Server's NodePort
    %EXPOSE_ADMIN_PORT_PREFIX%   - channelName: default
    %EXPOSE_ADMIN_PORT_PREFIX%     nodePort: %ADMIN_NODE_PORT%
    # Uncomment to export the T3Channel as a service
    %EXPOSE_T3_CHANNEL_PREFIX%   - channelName: T3Channel
    serverPod:
      # an (optional) list of environment variable to be set on the admin servers
      env:
      - name: USER_MEM_ARGS
        value: "-Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1024m "
      - name: CLASSPATH
        value: "/u01/oracle/wlserver/server/lib/weblogic.jar"

  configuration:
      secrets: [ %DOMAIN_UID%-rcu-credentials ]
      initializeDomainOnPV:
        persistentVolume:
          metadata:
              name: %DOMAIN_UID%-domain-pv
          spec:
            storageClassName: %DOMAIN_UID%-domain-storage-class
            capacity:
          # Total storage allocated to the persistent storage.
                storage: %STORAGE_SIZE%
          # Reclaim policy of the persistent storage
          # # The valid values are: 'Retain', 'Delete', and 'Recycle'
            persistentVolumeReclaimPolicy: %SAMPLE_STORAGE_RECLAIM_POLICY%
          # Persistent volume type for the persistent storage.
          # # The value must be 'hostPath' or 'nfs'.
          # # If using 'nfs', server must be specified.
            %NFS_PREFIX%nfs:
              %NFS_PREFIX%server: %SAMPLE_STORAGE_NFS_SERVER%
            %HOST_PATH_PREFIX%hostPath:
              path: "%SAMPLE_STORAGE_PATH%"
        persistentVolumeClaim:
          metadata:
              name: %DOMAIN_UID%-domain-pvc
          spec:
            storageClassName: %DOMAIN_UID%-domain-storage-class
            resources:
                requests:
                    storage: %STORAGE_SIZE%
            volumeName: %DOMAIN_UID%-domain-pv
        domain:
            # Domain | DomainAndRCU
            createIfNotExists: DomainAndRCU
            # Image containing WDT installer and Model files.
            domainCreationImages:
                - image: '%DOMAIN_CREATION_IMAGE%'
            domainType: OAM
  # References to Cluster resources that describe the lifecycle options for all
  # the Managed Server members of a WebLogic cluster, including Java
  # options, environment variables, additional Pod content, and the ability to
  # explicitly start, stop, or restart cluster members. The Cluster resource
  # must describe a cluster that already exists in the WebLogic domain
  # configuration.
  clusters:
  - name: %DOMAIN_UID%-oam-cluster
  - name: %DOMAIN_UID%-policy-cluster

  # The number of managed servers to start for unlisted clusters
  # replicas: 1

---
# This is an example of how to define a Cluster resource.
apiVersion: weblogic.oracle/v1
kind: Cluster
metadata:
  name: %DOMAIN_UID%-oam-cluster
  namespace: %NAMESPACE%
spec:
  clusterName: oam_cluster
  serverService:
    precreateService: true
  replicas: %INITIAL_MANAGED_SERVER_REPLICAS%
  serverPod:
    env:
    - name: USER_MEM_ARGS
      value: "-XX:+UseContainerSupport -Djava.security.egd=file:/dev/./urandom %OAMSERVER_JAVA_PARAMS% "
    resources:
      limits:
        cpu: "%OAM_MAX_CPU%"
        memory: "%OAM_MAX_MEMORY%"
      requests:
        cpu: "%OAM_CPU%"
        memory: "%OAM_MEMORY%"


---
# This is an example of how to define a Cluster resource.
apiVersion: weblogic.oracle/v1
kind: Cluster
metadata:
  name: %DOMAIN_UID%-policy-cluster
  namespace: %NAMESPACE%
spec:
  clusterName: policy_cluster
  serverService:
    precreateService: true
  replicas: %INITIAL_MANAGED_SERVER_REPLICAS%


