# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
# This is an example of how to define Active GridLink type datasources for OAM domain
# For details regarding how to work with WDT model files and WDT model attributes, please refer below links
# https://oracle.github.io/weblogic-kubernetes-operator/managing-domains/domain-on-pv/model-files/
# https://oracle.github.io/weblogic-deploy-tooling/concepts/model/
#

resources:
    JDBCSystemResource:
        LocalSvcTblDataSource:
            JdbcResource:
                DatasourceType: AGL
                JDBCConnectionPoolParams:
                    ConnectionReserveTimeoutSeconds: 10
                    InitialCapacity: 0
                    MaxCapacity: 400
                    TestConnectionsOnReserve: true
                    CapacityIncrement: 1
                    TestFrequencySeconds: 0
                    SecondsToTrustAnIdlePoolConnection: 0
                    TestTableName: SQL ISVALID
                JDBCOracleParams:
                    FanEnabled: true
                    ActiveGridlink: true
                JDBCDriverParams:
                    URL: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_host@@ )(PORT= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_port@@)))(CONNECT_DATA=(SERVICE_NAME= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_service@@)))'
        opss-audit-DBDS:
            JdbcResource:
                DatasourceType: AGL
                JDBCConnectionPoolParams:
                    TestFrequencySeconds: 0
                    TestConnectionsOnReserve: true
                    TestTableName: SQL ISVALID
                JDBCOracleParams:
                    FanEnabled: true
                    ActiveGridlink: true
                JDBCDriverParams:
                    URL: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_host@@ )(PORT= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_port@@)))(CONNECT_DATA=(SERVICE_NAME= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_service@@)))'
        opss-audit-viewDS:
            JdbcResource:
                DatasourceType: AGL
                JDBCConnectionPoolParams:
                    TestFrequencySeconds: 0
                    TestConnectionsOnReserve: true
                    TestTableName: SQL ISVALID
                JDBCOracleParams:
                    FanEnabled: true
                    ActiveGridlink: true
                JDBCDriverParams:
                    URL: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_host@@ )(PORT= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_port@@)))(CONNECT_DATA=(SERVICE_NAME= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_service@@)))'
        opss-data-source:
            JdbcResource:
                DatasourceType: AGL
                JDBCConnectionPoolParams:
                    TestFrequencySeconds: 0
                    TestConnectionsOnReserve: true
                    TestTableName: SQL ISVALID
                JDBCOracleParams:
                    FanEnabled: true
                    ActiveGridlink: true
                JDBCDriverParams:
                    URL: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_host@@ )(PORT= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_port@@)))(CONNECT_DATA=(SERVICE_NAME= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_service@@)))'
        WLSSchemaDataSource:
            JdbcResource:
                DatasourceType: AGL
                JDBCConnectionPoolParams:
                    MaxCapacity: 150
                    TestConnectionsOnReserve: true
                    TestFrequencySeconds: 0
                    TestTableName: SQL ISVALID
                JDBCOracleParams:
                    FanEnabled: true
                    ActiveGridlink: true
                JDBCDriverParams:
                    URL: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_host@@ )(PORT= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_port@@)))(CONNECT_DATA=(SERVICE_NAME= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_service@@)))'
        oamDS:
            JdbcResource:
                DatasourceType: AGL
                JDBCConnectionPoolParams:
                    MaxCapacity: 200
                    TestConnectionsOnReserve: true
                    TestTableName: SQL ISVALID
                    CapacityIncrement: 1
                    ConnectionCreationRetryFrequencySeconds: 10
                    InitialCapacity: 20
                    SecondsToTrustAnIdlePoolConnection: 0
                    TestFrequencySeconds: 0
                    InactiveConnectionTimeoutSeconds: 300
                JDBCOracleParams:
                    FanEnabled: true
                    ActiveGridlink: true
                JDBCDriverParams:
                    URL: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_host@@ )(PORT= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_port@@)))(CONNECT_DATA=(SERVICE_NAME= @@SECRET:@@ENV:DOMAIN_UID@@-rcu-credentials:db_service@@)))'
