# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
# This is an example of how to define the resource section in WDT Model for an OAM Domain
# For details regarding how to work with WDT model files and WDT model attributes, please refer below links
# https://oracle.github.io/weblogic-kubernetes-operator/managing-domains/domain-on-pv/model-files/
# https://oracle.github.io/weblogic-deploy-tooling/concepts/model/
#

resources:
    WebAppContainer:
        WeblogicPluginEnabled: true
