# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This is an example of how to define an OIG Domain. For details about the fields in domain specification, refer https://oracle.github.io/weblogic-kubernetes-operator/managing-domains/domain-resource/
#
apiVersion: "weblogic.oracle/v9"
kind: Domain
metadata:
  name: governancedomain
  namespace: oigns
  labels:
    weblogic.domainUID: governancedomain
spec:
  # The WebLogic Domain Home
  domainHome: /u01/oracle/user_projects/domains/governancedomain

  # The domain home source type
  # Set to PersistentVolume for domain-in-pv, Image for domain-in-image, or FromModel for model-in-image
  domainHomeSourceType: PersistentVolume

  # The WebLogic Server image that the Operator uses to start the domain
  image: "oracle/oig:oct23-12.2.1.4.0"

  # imagePullPolicy defaults to "Always" if image version is :latest
  imagePullPolicy: IfNotPresent

  imagePullSecrets:
  - name: orclcred
  # Identify which Secret contains the WebLogic Admin credentials
  webLogicCredentialsSecret:
    name: governancedomain-weblogic-credentials

  # Whether to include the server out file into the pod's stdout, default is true
  includeServerOutInPodLog: true

  # Whether to enable log home
  logHomeEnabled: true

  # Whether to write HTTP access log file to log home
  httpAccessLogInLogHome: true

  # The in-pod location for domain log, server logs, server out, introspector out, and Node Manager log files
  logHome: /u01/oracle/user_projects/domains/logs/governancedomain
  # An (optional) in-pod location for data storage of default and custom file stores.
  # If not specified or the value is either not set or empty (e.g. dataHome: "") then the
  # data storage directories are determined from the WebLogic domain home configuration.
  dataHome: ""

  # serverStartPolicy legal values are "Never, "IfNeeded", or "AdminOnly"
  # This determines which WebLogic Servers the Operator will start up when it discovers this Domain
  # - "Never" will not start any server in the domain
  # - "AdminOnly" will start up only the administration server (no managed servers will be started)
  # - "IfNeeded" will start all non-clustered servers, including the administration server and clustered servers up to the replica count
  serverStartPolicy: IfNeeded

  serverPod:
    initContainers:
      #DO NOT CHANGE THE NAME OF THIS INIT CONTAINER
      - name: compat-connector-init
        # OIG Product image, same as spec.image mentioned above
        image: "oracle/oig:oct23-12.2.1.4.0"
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "mkdir -p /u01/oracle/user_projects/domains/ConnectorDefaultDirectory", "mkdir -p  /u01/oracle/user_projects/domains/wdt-logs"]
        volumeMounts:
          - mountPath: /u01/oracle/user_projects/
            name: weblogic-domain-storage-volume
    # a mandatory list of environment variable to be set on the servers
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx1024m "
    - name: WLSDEPLOY_LOG_DIRECTORY
      value: "/u01/oracle/user_projects/domains/wdt-logs"
    - name: FRONTENDHOST
      value: "example.com"
    - name: FRONTENDPORT
      value: "14000"
    volumes:
    - name: weblogic-domain-storage-volume
      persistentVolumeClaim:
        claimName: governancedomain-domain-pvc
    volumeMounts:
    - mountPath: /u01/oracle/user_projects/
      name: weblogic-domain-storage-volume

  # adminServer is used to configure the desired behavior for starting the administration server.
  adminServer:
    # adminService:
    #   channels:
    # The Admin Server's NodePort
    #    - channelName: default
    #      nodePort: 30711
    # Uncomment to export the T3Channel as a service
    #    - channelName: T3Channel
    serverPod:
      # an (optional) list of environment variable to be set on the admin servers
      env:
      - name: USER_MEM_ARGS
        value: "-Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1024m "

  configuration:
      secrets: [ governancedomain-rcu-credentials ]
      initializeDomainOnPV:
        persistentVolume:
          metadata:
              name: governancedomain-domain-pv
          spec:
            storageClassName: governancedomain-domain-storage-class
            capacity:
          # Total storage allocated to the persistent storage.
                storage: 10Gi
          # Reclaim policy of the persistent storage
          # # The valid values are: 'Retain', 'Delete', and 'Recycle'
            persistentVolumeReclaimPolicy: Retain
          # Persistent volume type for the persistent storage.
          # # The value must be 'hostPath' or 'nfs'.
          # # If using 'nfs', server must be specified.
            nfs:
              path: /scratch/k8s_dir
              server: nfsServer
            #hostPath:
              #path: "/scratch/k8s_dir"
        persistentVolumeClaim:
          metadata:
              name: governancedomain-domain-pvc
          spec:
            storageClassName: governancedomain-domain-storage-class
            resources:
                requests:
                    storage: 10Gi
            volumeName: governancedomain-domain-pv
        domain:
            # Domain | DomainAndRCU
            createIfNotExists: Domain
            # Image containing WDT installer and Model files.
            domainCreationImages:
                - image: 'oracle/oig:oct23-aux-12.2.1.4.0'
            domainType: OIG
  # References to Cluster resources that describe the lifecycle options for all
  # the Managed Server members of a WebLogic cluster, including Java
  # options, environment variables, additional Pod content, and the ability to
  # explicitly start, stop, or restart cluster members. The Cluster resource
  # must describe a cluster that already exists in the WebLogic domain
  # configuration.
  clusters:
  - name: governancedomain-oim-cluster
  - name: governancedomain-soa-cluster

  # The number of managed servers to start for unlisted clusters
  # replicas: 1

---
# This is an example of how to define a Cluster resource.
apiVersion: weblogic.oracle/v1
kind: Cluster
metadata:
  name: governancedomain-oim-cluster
  namespace: oigns
spec:
  clusterName: oim_cluster
  serverService:
    precreateService: true
  replicas: 0
  serverPod:
    env:
    - name: USER_MEM_ARGS
      value: "-Djava.security.egd=file:/dev/./urandom -Xms4096m -Xmx8192m "

---
# This is an example of how to define a Cluster resource.
apiVersion: weblogic.oracle/v1
kind: Cluster
metadata:
  name: governancedomain-soa-cluster
  namespace: oigns
spec:
  clusterName: soa_cluster
  serverService:
    precreateService: true
  replicas: 1
  serverPod:
    env:
    - name: USER_MEM_ARGS
      value: "-Xms4096m -Xmx8192m"
