#
# Copyright (c) 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
{{- if .Values.persistence.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: {{ .Values.persistence.storageClass }}
    annotations:
      storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/is-default-class
{{- end }}
