#
# Copyright (c) 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#

--- 
{{- if .Values.cronJob.enabled }}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata: 
  name: oud-pod-cron-job
  namespace: {{ .Release.Namespace }}
spec: 
  jobTemplate: 
    spec: 
      template: 
        spec:
        {{- with .Values.cronJob.imagePullSecrets }}
          imagePullSecrets:
{{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "oud-ds-rs.serviceAccountName" . }}-job
          containers: 
            - name: cron-kubectl 
              command: 
                - "/bin/bash"
                - "-c"
                - "for i in `kubectl get pods -n {{ .Release.Namespace }} | grep oud | grep Terminating | awk '{print $1}'` ;do arr+=($i) ;done ;size=${#arr[@]} ;if [ ${size} -ge 1 ]; then for j in ${arr[@]} ; do `kubectl delete pod ${j##*.} --grace-period=0 --force -n={{ .Release.Namespace }}`; done;fi"
              image: "{{ .Values.cronJob.kubectlImage.repository }}:{{ .Values.cronJob.kubectlImage.tag }}"
              imagePullPolicy: {{ .Values.cronJob.kubectlImage.pullPolicy }}
          restartPolicy: OnFailure
  schedule: {{ .Values.cronJob.schedule }}
{{- end }}
