#
# Copyright (c) 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at 
# https://oss.oracle.com/licenses/upl
#

{{- if and .Values.cronJob.cronPersistence.enabled (not .Values.cronJob.cronPersistence.pvcname) }}
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "oud-ds-rs.fullname" . }}-job-pvc
{{- with .Values.cronJob.cronPersistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "oud-ds-rs.labels" . | nindent 4 }}
    type: {{ template "oud-ds-rs.fullname" . }}-job-pvc
spec:
{{- if .Values.cronJob.cronPersistence.storageClass }}
  storageClassName: {{ .Values.cronJob.cronPersistence.storageClass }}
{{- end }}
  selector:
    matchLabels:
      {{- include "oud-ds-rs.labels" . | nindent 6 }}
      type: {{ template "oud-ds-rs.fullname" . }}-job-pv
  accessModes:
    - {{ .Values.cronJob.cronPersistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.cronJob.cronPersistence.size | quote }}
{{- end }}
