#
# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl
#
#
{{- if .Values.elk.enabled }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: storage.k8s.io/v1
{{- else -}}
apiVersion: storage.k8s.io/v1beta1
{{- end }}
kind: StorageClass
metadata:
    name: {{ .Values.elkVolume.storageClass }}
    annotations:
      storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/is-default-class
parameters:
   repl: {{ .Values.elk.elasticsearch.esreplicas | quote }}
{{- end }}
